### PR TITLE
Update some bugs about Markdown syntax and spells

### PR DESCRIPTION
**Pull request by dominhhai**
Is the [contributions welcome link](https://github.com/ideaq/time/issues) correct?
It should be linked to its own issues instead of other repos's issues.

### CODE REVIEW

**Comment by iteles** [comment]
Hi @dominhhai, these are great, thanks for submitting the PR!

You're absolutely right about the contributions welcome link - that's what I get for copy-pasting across my projects! - I'll fix that :)

**Comment by dominhhai** [comment]
Thanks for your merging.
Your work is great! Keep running :+1:

**Comment by nelsonic** [comment]
:+1:

**Comment by iteles** [comment]
Thanks @dominhhai , that's very kind! :blush:

**Pull request merged**
