### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by rohitnz**
fixed typo: 'thro' - 'throw'

### CODE REVIEW

**Comment by karinakozarova** [comment]
Good job! I approve

**Comment by karinakozarova** [comment]
Wow, you're really good at catching these typos 👍 Keep up the good work

**Review by iteles — APPROVED** [review]
Thanks for picking up on these @rohitnz and thanks @karinakozarova for the review! 🎉 💃

**Comment by rohitnz** [comment]
@iteles Thank you for creating this condensed document. Very neat and useful.
@karinakozarova Thank you for reviewing changes and the extra cheer.

**Pull request merged**
